apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  annotations:
    volume.kubernetes.io/storage-class: "iscsi"
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 5Gi
