apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: flask
      targetPort: 5000
  externalIPs:
    - 192.168.11.120
    - 192.168.11.121
  selector:
    app: flask
