apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: mynginx-ingress
spec:
  rules:
    - host: hello.world
      http:
        paths:
          - path: /
            backend:
              serviceName: vue
              servicePort: 8080
          - path: /books
            backend:
              serviceName: flask
              servicePort: 5000
